// Auto-generated by scripts/generate_audio.js

export const audioMap = {
  "A city planner has a blueprint triangle with sides thirty, forty, and fifty metres.": "/assets/audio/audio_A_city_planner_has_a_blueprint_0.mp3",
  "A scale model shows six, eight, and ten centimetres. Are these triangles related?": "/assets/audio/audio_A_scale_model_shows_six__eight_1.mp3",
  "Let's uncover what makes two triangles similar, or exactly the same!": "/assets/audio/audio_Let_s_uncover_what_makes_two_t_2.mp3",
  "Tyler slides one triangle brace across the blueprint. It lands exactly on the second brace. Every point moved the same distance in the same direction — that's a Translation!": "/assets/audio/audio_Tyler_slides_one_triangle_brac_3.mp3",
  "Madison notices the two braces are mirror images. She reflects one triangle across the centre beam. Same shape, flipped side! That's a Reflection.": "/assets/audio/audio_Madison_notices_the_two_braces_4.mp3",
  "Brandon rotates a brace 90 degrees around a pivot bolt — and it matches perfectly! The shape turned but didn't stretch. That's a Rotation.": "/assets/audio/audio_Brandon_rotates_a_brace_90_deg_5.mp3",
  "Because a sequence of rigid motions maps one triangle exactly onto the other, the engineering team confirms: the triangles are Congruent!": "/assets/audio/audio_Because_a_sequence_of_rigid_mo_6.mp3",
  "Jordan compares the full-size bridge brace to a scale model brace half the size. A Dilation stretched one triangle to match the other!": "/assets/audio/audio_Jordan_compares_the_full_size__7.mp3",
  "A dilation plus rigid motions maps one triangle onto the other, so they are Similar! Same angles, proportional sides — Riley can calculate real distances from the scale model.": "/assets/audio/audio_A_dilation_plus_rigid_motions__8.mp3",
  "Station complete! Moving to the next challenge.": "/assets/audio/audio_Station_complete__Moving_to_th_9.mp3",
  "Outstanding! You have completed all four simulation stations!": "/assets/audio/audio_Outstanding__You_have_complete_10.mp3",
  "Exactly right! The triangles match!": "/assets/audio/audio_Exactly_right__The_triangles_m_11.mp3",
  "Not quite. Check the ratio of corresponding sides.": "/assets/audio/audio_Not_quite__Check_the_ratio_of__12.mp3",
  "Correct! Well done!": "/assets/audio/audio_Correct__Well_done__13.mp3",
  "Not quite. Multiply the known side by the scale factor.": "/assets/audio/audio_Not_quite__Multiply_the_known__14.mp3",
  "Excellent! A perfectly structured proof!": "/assets/audio/audio_Excellent__A_perfectly_structu_15.mp3",
  "Some steps are out of place. Check the highlighted rows.": "/assets/audio/audio_Some_steps_are_out_of_place__C_16.mp3",
  "Perfect! All criteria identified correctly!": "/assets/audio/audio_Perfect__All_criteria_identifi_17.mp3",
  "Check the highlighted cards — some are incorrect.": "/assets/audio/audio_Check_the_highlighted_cards____18.mp3",
  "Correct!": "/assets/audio/audio_Correct__19.mp3",
  "Not quite.": "/assets/audio/audio_Not_quite__20.mp3",
  "Lesson complete! You are a Proof Champion!": "/assets/audio/audio_Lesson_complete__You_are_a_Pro_21.mp3"
};
